repos:
  - repo: local
    hooks:
      - id: unittest
        name: Run Unittest
        # "discover" finds all files matching the pattern
        entry: uv run python -m unittest discover -s tests -p "test*.py"
        language: system
        types: [ python ]
        pass_filenames: false
        verbose: true